"""add feedback table

Revision ID: b37446742892
Revises: 9b1125c99599
Create Date: 2024-01-02 11:56:06.952698+00:00
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b37446742892"
down_revision = "9b1125c99599"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feed_back",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("send_time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feed_back_id"), "feed_back", ["id"], unique=False)
    op.drop_index("ix_user_chat_id", table_name="users")
    op.create_index(op.f("ix_users_chat_id"), "users", ["chat_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_chat_id"), table_name="users")
    op.drop_index(op.f("ix_feed_back_id"), table_name="feed_back")
    op.drop_table("feed_back")
    # ### end Alembic commands ###
