"""users table: optional username

Revision ID: c06a814007e2
Revises: bfa902e56da6
Create Date: 2024-01-28 10:18:20.455309+00:00
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c06a814007e2"
down_revision = "bfa902e56da6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
