"""add bot session table

Revision ID: bfa902e56da6
Revises: b37446742892
Create Date: 2024-01-20 11:36:44.969972+00:00
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bfa902e56da6"
down_revision = "b37446742892"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_session",
        sa.Column("session", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("session"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bot_session")
    # ### end Alembic commands ###
